### ISSUE TITLE
Date js doesn't seem to be working

### ISSUE THREAD

**Issue by pspeter3** [chrisdew/datejs#2]
I'm using date.js v0.0.2 and I've done `require('datejs');`. However, `new Date().moveToBeginningOfMonth();` is not working and says that the date does not have that method.

**Comment by chrisdew** [comment]
Yes, all of DateJS is not working in 0.4.x - I'm now investigating it.

**Comment by pspeter3** [comment]
It strangely seemed to work after I uninstalled and reinstalled version 0.0.2

**Comment by chrisdew** [comment]
test case:

chris@chris-linux-desktop:~/testdir$ node -v
v0.4.8

chris@chris-linux-desktop:~/testdir$ cat test.js 
require('datejs');
var date = new Date().moveToBeginningOfMonth();
console.log(date);

chris@chris-linux-desktop:~/testdir$ node test.js

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object Tue Oct 18 2011 12:22:02 GMT+0100 (BST) has no method 'moveToBeginningOfMonth'
    at Object.<anonymous> (/home/chris/testdir/test.js:2:23)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at Array.<anonymous> (module.js:426:10)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by chrisdew** [comment]
I still see the error after upgrading to Node 0.4.12.

**Comment by chrisdew** [comment]
It seems to be an issue with adding methods to prototypes...

(adapted from http://www.datejs.com/ )

var djs = require('datejs');
console.log("What date is next thrusday?", Date.today().next().thursday());
console.log("Add 3 days to Today", Date.today().add(3).days());
console.log("Is today Friday?", Date.today().is().friday());
console.log("Number fun", (3).days().ago());
var n = 6;
console.log("6 months from now", n.months().fromNow());
console.log("Set to 8:30 AM on the 15th day of the month", Date.today().set({ day: 15, hour: 8, minute: 30 }));
console.log("today", Date.parse('today'));
console.log("t + 5 d", Date.parse('t + 5 d')); // today + 5 days
console.log("next thursday", Date.parse('next thursday'));
console.log("February 20th 1973", Date.parse('February 20th 1973'));
console.log("Thu, 1 July 2004 22:30:00", Date.parse('Thu, 1 July 2004 22:30:00'));

produces:

What date is next thrusday? { Wed, 19 Oct 2011 23:00:00 GMT _orient: 1 }
Add 3 days to Today { Thu, 20 Oct 2011 23:00:00 GMT _orient: 3 }
Is today Friday? false
Number fun Tue, 18 Oct 2011 11:42:27 GMT
6 months from now Tue, 18 Oct 2011 11:42:27 GMT
Set to 8:30 AM on the 15th day of the month Sat, 15 Oct 2011 07:30:00 GMT
today Mon, 17 Oct 2011 23:00:00 GMT
t + 5 d Sat, 22 Oct 2011 23:00:00 GMT
next thursday Wed, 19 Oct 2011 23:00:00 GMT
February 20th 1973 Tue, 20 Feb 1973 00:00:00 GMT
Thu, 1 July 2004 22:30:00 Thu, 01 Jul 2004 21:30:00 GMT

Some of the above are wrong.

**Comment by chrisdew** [comment]
Correction, only "6 months from now Tue, 18 Oct 2011 11:42:27 GMT" is wrong.  I was confused by my machine being BST.

**Comment by chrisdew** [comment]
@pspeter3 could you show me why you think "new Date().moveToBeginningOfMonth();" should work?

**Comment by chrisdew** [comment]
@pspeter3 I think you may have meant moveToFirstDayOfMonth

I'll re-open this if I'm wrong.
