### ISSUE TITLE
datejs no longer available through npm registry

### ISSUE THREAD

**Issue by rfadams** [chrisdew/datejs#3]
Hello

I did a `npm install datejs` a couple days ago on a new project and all worked out. Then today I'm moving some code up to the server and tried it again. Now I'm getting:

```
npm ERR! 404 'datejs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
```

So here I am. Was it taken down on purpose?

**Comment by iangreenleaf** [comment]
:+1:

**Comment by chrisdew** [comment]
Yes, I unpublished it as there was a bug, that multiple people
werecomplaining about, that I could't fix (after several hours
trying).
I was just getting very tired of the email stream, legitimately
askingabout when I would fix it.
if you or anyone else would like to take over this simple
wrapperproject, I'd be glad to pass it on...
Sorry for inconveniencing you.
Chris.
On 18 October 2011 04:07, Robert Adams
reply@reply.github.com
wrote:

**Comment by chrisdew** [comment]
I've npm published it again, as not everyone seems to be suffering from show-shopping issue #2.

Is there an option to mark an npm package as 'it's got a show-stopping bug I can't fix, but it still works for some people'?

**Comment by rfadams** [comment]
I could take a look at it. 

How do you reproduce the bug? I'm currently using node v0.4.7 and I'm not having any problems, but I haven't used `new Date().moveToBeginningOfMonth();` yet either. 

Robert

**Comment by chrisdew** [comment]
Hi Robert,

I'll have another bash at it in a couple of minutes and get back to
you.  The bug affected every function which DateJS pushed on to Date's
prototype.

Thanks for your offer of help,

Chris.

On 18 October 2011 12:02, Robert Adams
reply@reply.github.com
wrote:

**Comment by rfadams** [comment]
Hmm. That's very odd, I'm definitely using some of DateJS's custom methods. I wonder why I haven't run into it. 

I'm kinda new to nodejs, but I could probably take a look at it tomorrow night. Let me know if you have any luck. 

Thanks again. Definitely appreciate you getting the project this far. 

Robert

**Comment by chrisdew** [comment]
Have a look at:

https://github.com/chrisdew/datejs/issues/2

if you get a spare minute.

Thanks,

Chris.

On 18 October 2011 12:17, Robert Adams
reply@reply.github.com
wrote:

**Comment by rfadams** [comment]
Ok, thanks for the info. I'll take a look at it tomorrow night, hopefully. I'm about to crash. Work in a few hours. 

Robert

**Comment by chrisdew** [comment]
I think https://github.com/chrisdew/datejs/issues/2 is solved.

But there is still one little bug:
https://github.com/chrisdew/datejs/issues/4 but it's not a show
stopper.

Thanks for your offer, anyway.

All the best,

Chris.

On 18 October 2011 12:47, Robert Adams
reply@reply.github.com
wrote:
